### ISSUE TITLE
Binary data uploading blobId issue

### ISSUE THREAD

**Issue by jeserkin** [OpenPaaS-Suite/jmap-client-ts#50]
It feels like a bug, but I am not sure.

So the use case is editing one draft multiple times. Since emails are immutable to a certain degree in James, the only way at the moment, that I was able to find is to create new email with `Email/set` -> `create` and remove previous version with `Email/set` -> `destroy`.

Now moving and focusing on attachments.
When uploading binary data successfully one does receive response in a form:
```json
{
  "accountId":"5a20d72b9605345c1b526c6cba0565f699dfbde43f735d68c689dada5b3bfb85",
  "blobId":"lxcmnvkkfkudryrqttcj",
  "type":"text/css",
  "size":29
}
```

Adding this response with additional `name` property as attachment for `Email/set` -> `create` works fine, but attachments, that come back with `Email/get` have following structure:
```json
{
  "charset": "us-ascii",
  "disposition": "attachment",
  "size": 8480,
  "partId": "5",
  "blobId": "0207d9f0-9757-11eb-a1b2-658a285e665b_5",
  "name": "Book1.xlsx",
  "type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
}
```
Here `blobId` looks differently.

Now the issue itself is with doing `Email/set` -> `create` with attachments, where `blobId` is e.g. "0207d9f0-9757-11eb-a1b2-658a285e665b_5"
Response is negative `invalidArguments` ... `Attachment not found: 0207d9f0-9757-11eb-a1b2-658a285e665b_5`

So I guess the question is, whether it is James configuration issue or whether it is flawed logic on my part or something else?

**Comment by chibenwa** [comment]
> Here blobId looks differently.

Blob storaged is backed by several blob resolvers:

 - One for message blobs
 - One for attachments (uploaded as well as those extracted upon mailbox::append)
 - One for mime parts
 
They are backed by different syntaxes here.

> Response is negative invalidArguments ... Attachment not found: 0207d9f0-9757-11eb-a1b2-658a285e665b_5

The issue is well known: Email/set create is using solely the attachment resolver and not the other blob resolvers. Here `0207d9f0-9757-11eb-a1b2-658a285e665b_5` is backed by the mime part blob resolver.

See https://github.com/apache/james-project/pull/362 https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3537

This should gets merged timely...

**Comment by chibenwa** [comment]
BTW the right place to discuss James related bugs is https://issues.apache.org/jira/projects/JAMES/issues/ :-)

**Comment by jeserkin** [comment]
I see. Very good news then. Asked here, since I wasn't sure whether it is James related or my miss use of JMAP documentation
